### ISSUE TITLE
remover

### ISSUE THREAD

**Issue by jjups96** [rexemin/ArbolBNoRecursivo#1]
## Al remover ciertas llaves se rompe el programa.
**CHECAR LOS VALORES MOVIDOS DEL REACOMODO/LIMITE DE DE LLAVES.
Posiblemente es que intente acceder a un lugar sin key.**

de la linea 154 de main.cpp
a la linea 375 de BTree.cpp
a la linea 303 de BTree.cpp
a la linea 349 de BTreeNode.cpp

Cuando intentamos remover llegamos a la parte de la funcion remove
if (current->Children[index]->numKeys < degree/2 - 1) {
                current->fill(index);
}
 y  fill intenta hacer
if (index != 0 && Children[index - 1]->numKeys >= degree) {
        borrowFromPrev(index);
}

**Comment by rexemin** [comment]
Los problemas en las funciones auxiliares del remover han sido arregladas.
Todo tenía que ver con índices fuera de rango y un grado mínimo erróneo.
